name = "CanopyOptics"
uuid = "a18e34a6-5dbe-4f38-a44b-e5141852e7a7"
authors = ["cfranken "]
version = "0.1.3"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DiffRules = "b552c78f-8df3-52c6-915a-8e097449b14b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulEquivalences = "da9c4bc3-91c8-4f02-8a40-6b990d2a7e0c"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
CUDA = "3,4"
DiffRules = "1.15"
Distributions = "0.25"
DocStringExtensions = "0.8, 0.9"
FastGaussQuadrature = "0.4"
Parameters = "0.12"
Polynomials = "2, 3"
QuadGK = "2"
SpecialFunctions = "2"
UnicodePlots = "3"
Unitful = "1"
UnitfulEquivalences = "0.2"
YAML = "0.4"
julia = "1.7, 1.8, 1.9"
ForwardDiff = "0.10"
